---
language: python
python: "2.7"

# This role needs sudo, thus we can't use the new container infrastructure
# sudo: false
sudo: required

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

  # Resolve dependencies(When target role isn't installed via Ansible Galaxy, auto resolution of dependencies doesn't occur.
  - ansible-galaxy install futurice.pip

  # Change directory name to fit role name
  - mv ../ansible-ansible ../ansible

before_script:
  - docker run -it -d --name container python:2 /bin/bash
  # Workaround: Docker connection plugin of Ansible requires that
  # Python is installed at specified path(/usr/bin/python) in the target container
  - docker exec container ln -s /usr/local/bin/python /usr/bin/python

script:
  # Basic role syntax check
  - ansible-playbook tests/travis.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/travis.yml -i tests/inventory --connection=docker -vvvv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
