---
# tasks file for ansible
- name: Install requirements for Ansible from apt
  apt: name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - python-dev
  become: yes

- name: Install Ansible
  pip: name=ansible
