---
# tasks file for ansible
# TODO: This should be moved to another role.
- name: Install requirement for Ansible apt module
  # Playbook using this role should remove cache like:
  # rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/apt/archives/*
  shell: apt-get update && apt-get install -y python-apt --no-install-recommends
  become: yes
- name: Install requirements for Ansible from apt
  apt: name={{ item }} update_cache=yes
  with_items:
    - build-essential
    - python-dev
  become: yes

- name: Install Ansible
  pip: name=ansible
